---

- name: uninstall_golang_from_distrib_repo
  package:
    name: golang-go
    state: absent
  become: True
  when: pack_purge == "True"
  tags: 
    - purge_go
    - purge_golang
    - purge

- name: uninstall_gccgo_go_from_distrib_repo
  package:
    name: gccgo-go
    state: absent
  become: True
  when: pack_purge == "True"
  tags:
    - purge_go
    - purge_gccgo
    - purge

- name: install_go_from_snap
  command: "snap install go --classic"
  become: True
  #when: ansible_version.full is version('2.8.0', '>=')
  tags:
    - install_go_snap

- name: ensure_variables_in_profile
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  with_items:
    - 'export GOPATH=/usr/local/go/bin'
    - 'export PATH=$PATH:/usr/local/go/bin'
  #  - 'export GOROOT=/usr/local/go'
  become: True
  tags:
    - ensure_variables_in_profile

- name: ensure_godir_exists
  file:
    path: '/usr/local/go/bin'
    state: directory
    mode: '0755'
  tags:
    - ensure_godir_exists

- name: install_go_dependecies
  shell: 'go get github.com/go-sql-driver/mysql'
  environment:
    #GOROOT: '/usr/local/go'
    PATH: '{{ ansible_env.PATH }}:/snap/bin'
    GOPATH: '/usr/local/go/bin'
  register: cmd_result
  become: True
  tags:
    - install_go_dependecies

- name: debugging
  debug:
    msg: '{{ cmd_result }}'
