---


- name: find_all_sql_instruction_sets
  shell: 'ls -v ../database/ | grep sql'
  register: sql_set

- name: set_sql_set
  set_fact:
    sql_set_file: '{{ sql_set.stdout_lines | sort }}'

- name: print_sql_files
  debug:
    msg: '{{ sql_set_file }}'

- name: iterate_over_files
  shell: 'cat ../database/{{ item }}'
  with_items: '{{ sql_set_file }}'
  register: file_contents

- name: d1
  debug:
    msg: '{{ file_contents }}'
