CREATE USER 'sailmaster-user'@'localhost' IDENTIFIED BY 'TYPE_DB_USER_PASSWORD_HERE';
GRANT USAGE ON *.* TO 'sailmaster-user'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `sailmaster`.* TO 'sailmaster-user'@'localhost';
