name: k6

on: [push]

jobs:
  build:
    name: Load-test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r webserver/requirements.txt

    - name: Run webserver
      working-directory: ./webserver
      run: nohup python3 webserver_auth.py&
   
    - name: CURL localhost
      run: curl http://localhost:6689/api/v1.0/heartbeat
      
    - name: CURL 127
      run: curl http://127.0.0.1:6689/api/v1.0/heartbeat

    - name: ls lap 0
      working-directory: /home/runner/work/Sailmaster/Sailmaster/webserver
      run: ls -lap


    - name: pwd
      working-directory: /home/runner/work/Sailmaster/Sailmaster/webserver/k6-tests
      run: pwd

    - name: ls lap
      working-directory: /home/runner/work/Sailmaster/Sailmaster/webserver/k6-tests
      run: ls -lap

    - name: Run k6
      #working-directory: ./webserver
      # --env AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}
      run: docker run -v /home/runner/work/Sailmaster/Sailmaster/webserver/k6-tests/docker.js:/docker.js -i loadimpact/k6 run docker.js
