name: k6

on: [push]

jobs:
  build:
    name: Load-test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r webserver/requirements.txt

    - name: Run webserver
      working-directory: ./webserver
      run: nohup python3 webserver_auth.py&

    - name: PWD
      run: pwd

    - name: lsla
      run: ls -la
    
    - name: Run k6
      #working-directory: ./webserver
      # --env AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}
      run: docker run -v /webserver/test.js:/test.js -i loadimpact/k6 run test.js
