name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r webserver/requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint webserver/webserver_auth.py --fail-under=6
    - name: Search for Errors with pylin–µ
      run: |
        pylint webserver/webserver_auth.py --errors-only
